name: Build CeeCash App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install -y zip unzip openjdk-11-jdk python3-pip
          python -m pip install --upgrade pip
          pip install --upgrade Cython kivy buildozer kivy_garden
          garden install webview || echo "Webview install failed"
          garden install sidebar || echo "Sidebar install failed"

      - name: Grant Execute Permissions
        run: |
          chmod +x ~/.local/bin/buildozer || echo "Buildozer not found"

      - name: Initialize Buildozer
        run: |
          buildozer init
          cat buildozer.spec  

      - name: Build APK with Buildozer
        run: |
          chmod +x ./buildozer
          buildozer -v android debug || (cat ~/.buildozer/android/platform/python-for-android/dists/*/build.log && exit 1)

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CeeCash-APK
          path: bin/*.apk
