# Code Refactored

name: Build CeeCash App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies and Buildozer
        run: |
          sudo apt update && sudo apt install -y zip unzip openjdk-11-jdk python3-pip libffi-dev libssl-dev libncurses5
          pip install --upgrade pip
          pip install Cython kivy buildozer kivy_garden
          for garden in webview sidebar; do
            kivy_garden install "$garden" || echo "Failed to install garden:$garden"
          done

      - name: Confirm buildozer.spec exists
        run: |
          [ -f buildozer.spec ] || buildozer init

      - name: Build APK with Buildozer
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          buildozer android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cee_cash
          path: bin/*.apk
