# Code Refactored

name: Build CeeCash App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install -y zip unzip openjdk-11-jdk python3-pip libffi-dev libssl-dev
          python -m pip install --upgrade pip
          pip install --upgrade Cython kivy buildozer kivy_garden
          for garden in webview sidebar; do
            kivy_garden install "$garden" || echo "Failed to install garden: $garden"
          done

      - name: Grant Execute Permissions
        run: |
          chmod +x ~/.local/bin/buildozer || echo "Buildozer not found"

      - name: Validate Buildozer Configuration
        run: |
          if [ -f buildozer.spec ]; then
            echo "Using existing buildozer.spec"
          else
            echo "Error: buildozer.spec not found!" && exit 1
          fi

      - name: Build APK with Buildozer
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          buildozer -v android debug || echo "Buildozer build failed"

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cee_cash
          path: bin/*.apk
