name: Build CeeCash App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install kivy buildozer cython
          pip install kivy_garden
          garden install webview
          garden install sidebar

      - name: Install Buildozer dependencies
        run: |
          sudo apt update && sudo apt install -y buildozer zip unzip openjdk-11-jdk python3-pip

      - name: Initialize Buildozer
        run: buildozer init

      - name: Build APK with Buildozer
        run: buildozer -v android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CeeCash-APK
          path: bin/*.apk
