# buildozer.spec

title: cee cash
package:
  name: ceecash_app
  domain: com.wuaze.ceecash

source:
  include_exts: 
    - py
    - png
    - jpg
    - kv
    - atlas
    - gif
    - mp4

requirements: 
  - python3
  - kivy
  - kivy-garden
  - kivy-garden.webview

android:
  permissions: 
    - INTERNET
  app_icon: icon.jpg
  splash_screen:
    image: splash.mp4
    fullscreen: true

orientation: portrait

# Ensure Buildozer is accessible from the root directory
buildozer_path: ./buildozer.spec
