name: cee_cash
version: 1.0
description: A Kivy application with a sidebar and web view functionality.
author: Your Name
requirements:
  - kivy
  - kivy_garden.webview
  - kivy_garden.sidebar
source:
  - main.py
buildozer:
  requirements: python3,kivy,kivy_garden.webview,kivy_garden.sidebar
  android:
    permissions:
      - INTERNET
